services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obeeoma_frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://64.225.122.101:8000