import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Navbar, Nav, Container } from 'react-bootstrap';
import { NavLink, Link } from 'react-router-dom';
import logo from '../../assets/Images/obeeomalogoicon2.png';
const AuthLayout = ({ children }) => {
<<<<<<< HEAD
    return (_jsxs("div", { className: "min-vh-100 d-flex flex-column bg-light", children: [_jsx(Navbar, { bg: "ob", variant: "success", expand: "lg", className: "border-bottom", children: _jsxs(Container, { children: [_jsx(Navbar.Brand, { as: NavLink, to: "/", className: "d-flex align-items-center", children: _jsxs("div", { className: "d-flex align-items-center", children: [_jsx("img", { src: logo, alt: "Obeeoma Logo", width: "35", className: "me-2" }), _jsx("div", { children: _jsx("small", { className: "text-muted", children: "A Happy Heart" }) })] }) }), _jsx(Navbar.Toggle, { "aria-controls": "basic-navbar-nav" }), _jsx(Navbar.Collapse, { id: "basic-navbar-nav", children: _jsxs(Nav, { className: "ms-auto", children: [_jsx(Nav.Link, { as: NavLink, to: "/about", children: "About" }), _jsx(Nav.Link, { as: NavLink, to: "/faqs", children: "FAQs" })] }) })] }) }), _jsx("main", { className: "flex-grow-1 d-flex align-items-center justify-content-center py-4", children: children }), _jsx("footer", { className: "bg-success text-light py-4 mt-auto", children: _jsx(Container, { children: _jsxs("div", { className: "text-center", children: [_jsx("p", { className: "mb-2", children: "\u00A9 2025 Obeeoma. All rights reserved." }), _jsxs("div", { className: "d-flex justify-content-center align-items-center flex-wrap gap-3", children: [_jsx(Nav.Link, { as: Link, to: "/privacy-policy", className: "text-light p-0 small", children: "Privacy Policy" }), _jsx("span", { className: "text-muted", children: "|" }), _jsx(Nav.Link, { as: Link, to: "/terms", className: "text-light p-0 small", children: "Terms of Service" }), _jsx("span", { className: "text-muted", children: "|" }), _jsx(Nav.Link, { as: Link, to: "/contact", className: "text-light p-0 small", children: "Contact Us" })] })] }) }) })] }));
=======
    return (_jsxs("div", { className: "min-vh-100 d-flex flex-column bg-light", children: [_jsx(Navbar, { bg: "ob", variant: "success", expand: "lg", className: "border-bottom", children: _jsxs(Container, { children: [_jsx(Navbar.Brand, { as: NavLink, to: "/", className: "d-flex align-items-center", children: _jsxs("div", { className: "d-flex align-items-center", children: [_jsx("img", { src: logo, alt: "Obeeoma Logo", width: "35", className: "me-2" }), _jsx("div", { children: _jsx("small", { className: "text-muted", children: "A Happy Heart" }) })] }) }), _jsx(Navbar.Toggle, { "aria-controls": "basic-navbar-nav" }), _jsx(Navbar.Collapse, { id: "basic-navbar-nav", children: _jsxs(Nav, { className: "ms-auto", children: [_jsx(Nav.Link, { as: NavLink, to: "/about", children: "About" }), _jsx(Nav.Link, { as: NavLink, to: "/faqs", children: "FAQs" })] }) })] }) }), _jsx("main", { className: "flex-grow-1 col-12 d-flex align-items-center justify-content-center py-4", children: children }), _jsx("footer", { className: "bg-success text-light py-4 mt-auto", children: _jsx(Container, { children: _jsxs("div", { className: "text-center", children: [_jsx("p", { className: "mb-2", children: "\u00A9 2025 Obeeoma. All rights reserved." }), _jsxs("div", { className: "d-flex justify-content-center align-items-center flex-wrap gap-3", children: [_jsx(Nav.Link, { as: Link, to: "/privacy-policy", className: "text-light p-0 small", children: "Privacy Policy" }), _jsx("span", { className: "text-muted", children: "|" }), _jsx(Nav.Link, { as: Link, to: "/terms", className: "text-light p-0 small", children: "Terms of Service" }), _jsx("span", { className: "text-muted", children: "|" }), _jsx(Nav.Link, { as: Link, to: "/contact", className: "text-light p-0 small", children: "Contact Us" })] })] }) }) })] }));
>>>>>>> syda
};
export default AuthLayout;
