import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
const Login = () => {
    const [role, setRole] = useState("Client");
    return (_jsx("div", { className: "min-h-screen flex items-center justify-center bg-gray-50", children: _jsxs("div", { className: "max-w-6xl w-full grid grid-cols-1 md:grid-cols-2 bg-white shadow-md rounded-lg overflow-hidden", children: [_jsxs("div", { className: "p-8", children: [_jsx("h2", { className: "text-2xl font-semibold mb-2", children: "Sign in to your account" }), _jsx("p", { className: "text-gray-600 mb-6", children: "Welcome back to Obeeoma" }), _jsxs("form", { className: "space-y-4", children: [_jsx("input", { type: "text", placeholder: "Username", className: "w-full px-4 py-2 border rounded-lg focus:outline-none" }), _jsx("input", { type: "password", placeholder: "Password", className: "w-full px-4 py-2 border rounded-lg focus:outline-none" }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("button", { type: "button", onClick: () => setRole("Client"), className: `px-4 py-2 rounded-lg ${role === "Client"
                                                ? "bg-green-100 text-green-700"
                                                : "bg-gray-100"}`, children: "Employer" }), _jsx("button", { type: "button", onClick: () => setRole("Organization"), className: `px-4 py-2 rounded-lg ${role === "Organization"
                                                ? "bg-green-100 text-green-700"
                                                : "bg-gray-100"}`, children: "Employee" })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("label", { className: "flex items-center space-x-2", children: [_jsx("input", { type: "checkbox", className: "rounded" }), _jsx("span", { children: "Remember me" })] }), _jsx("a", { href: "#", className: "text-green-600 text-sm hover:underline", children: "Forgot your password?" })] }), _jsx("button", { type: "submit", className: "w-full bg-green-600 text-white py-2 rounded-lg hover:bg-green-700 transition", children: "Sign in" })] }), _jsxs("p", { className: "mt-4 text-center text-gray-600", children: ["Don\u2019t have an account?", " ", _jsx("a", { href: "#", className: "text-green-600 font-medium hover:underline", children: "Create an account" })] })] }), _jsxs("div", { className: "p-8 bg-green-50", children: [_jsx("h3", { className: "text-xl font-semibold mb-4", children: "Welcome Back" }), _jsx("p", { className: "text-gray-600 mb-4", children: "Sign in to access your personalized mental health dashboard, connect with your care team, and continue your wellness journey." }), _jsxs("ul", { className: "space-y-2 text-gray-700", children: [_jsx("li", { children: "\u2714 Access your care plan" }), _jsx("li", { children: "\u2714 Schedule appointments" }), _jsx("li", { children: "\u2714 Message your care team" })] })] })] }) }));
};
export default Login;
