import React, { useEffect, useState } from "react";
import { Button, Card, Form, Alert, Spinner } from "react-bootstrap";
import { useAppDispatch, useAppSelector } from "../../hooks/redux-hooks";
import { setupMfa, confirmMfa } from "../../store/slices/authSlice";
import logo from "./../../assets/Images/obeeomalogoword1.png";

const MfaSetupPage: React.FC = () => {
  const dispatch = useAppDispatch();
  const {
    mfaSetupData,
    isLoading,
    error,
    isMfaSetupConfirmed,
    // user // Assuming user is available in authSlice
  } = useAppSelector((state) => state.auth);

  const [confirmationCode, setConfirmationCode] = useState("");

  // 1. Fetch QR Code data on component mount
  useEffect(() => {
    // Only fetch if data is not already present and not confirmed
    if (!mfaSetupData && !isMfaSetupConfirmed) {
      dispatch(setupMfa());
    }
  }, [dispatch, mfaSetupData, isMfaSetupConfirmed]);

  // 2. Handle Confirmation Submission
  const handleConfirmMfa = async (e: React.FormEvent) => {
    e.preventDefault();
    if (confirmationCode.length !== 6 || isLoading || !mfaSetupData) return;

    const payload = {
      temp_token: mfaSetupData.temp_token,
      code: confirmationCode,
    };

    // Dispatch the confirm thunk
    const result = await dispatch(confirmMfa(payload));

    if (confirmMfa.fulfilled.match(result)) {
      alert("MFA successfully! Redirecting...");
      // Navigation should happen here, e.g., navigate('/settings');
    }
  };

  const handleCodeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setConfirmationCode(e.target.value.replace(/\D/g, "").substring(0, 6));
  };

  // RENDER STATES

  if (isMfaSetupConfirmed) {
    return (
      <Alert variant="success" className="text-center p-5" style={{fontFamily:'body'}}>
        <h4>Multi-Factor Authentication is Active!</h4>
        <p>Your account is now protected. You can close this window.</p>
        <Button
          variant="success"
          onClick={() => (window.location.href = "/system-admin")}
        >
          CLOSE
        </Button>
      </Alert>
    );
  }

  if (isLoading && !mfaSetupData) {
    return (
      <div className="d-flex justify-content-center align-items-center vh-100" style={{fontFamily:'body'}}>
        <Spinner animation="border" />{" "}
        <span>&nbsp; Loading MFA setup data...</span>
      </div>
    );
  }

  return (
    <div
      className="d-flex justify-content-center align-items-center vh-100 p-3"
      style={{ backgroundColor: "#f5f5f5", fontFamily:'body'}}
    >
      <Card
        className="shadow-sm p-4"
        style={{ maxWidth: "600px", width: "100%", borderRadius: "8px", fontFamily:'body' }}
      >
        <div className="d-flex flex-column align-items-center justify-content-center mb-4">
          <img
            src={logo}
            alt="Logo"
            style={{ height: "50px", width: "auto" }}
            className="mb-1"
          />
        </div>
        <Card.Body>
          <h3 className="text-center mb-4 fw-semibold" style={{fontFamily:'heading'}}>
            Two-Factor Authentication
          </h3>

          {error && <Alert variant="danger" style={{fontFamily:'body'}}>{error}</Alert>}

          <p className="text-center text-muted mb-4" style={{fontFamily:'body'}}>
            Scan the QR code below using an authenticator app.if you haven't set
            it up yet,
          </p>

          {mfaSetupData ? (
            <div className="text-center">
              {/* QR Code Display: Uses the base64 data from the backend */}
              {mfaSetupData.qr_code_base64 ? (
                <div className="qr-code p-3 border rounded mb-3 bg-white" style={{fontFamily:'body'}}>
                  <img
                    src={`data:image/png;base64,${mfaSetupData.qr_code_base64}`}
                    alt="MFA Setup QR Code"
                    style={{ maxWidth: "200px", height: "200px" }}
                    className="img-fluid"
                  />
                </div>
              ) : null}

              {/* Manual Secret Key */}
              <Alert variant="info" className="p-2 mb-4" style={{fontFamily:'body'}}>
                Manual Key: <code>{mfaSetupData.secret}</code>
              </Alert>

              <Form onSubmit={handleConfirmMfa}>
                <Form.Group className="mb-3">
                  <Form.Control
                    type="text"
                    placeholder="6-digit verification code"
                    value={confirmationCode}
                    onChange={handleCodeChange}
                    maxLength={6}
                    inputMode="numeric"
                    className="text-center py-2"
                    style={{ fontSize: "1.2rem", letterSpacing: "6px", fontFamily:'body' }}
                    required
                    disabled={isLoading}
                  />
                  <Form.Text className="text-muted" style={{fontFamily:'body'}}>
                    Enter the code generated by your authenticator app to
                    confirm setup.
                  </Form.Text>
                </Form.Group>

                <Button
                  type="submit"
                  disabled={isLoading || confirmationCode.length < 6}
                  className="w-100 mt-3"
                  style={{ backgroundColor: "#22C55E", borderColor: "#22C55E" }}
                >
                  {isLoading ? (
                    <Spinner as="span" animation="border" size="sm" />
                  ) : (
                    "Confirm "
                  )}
                </Button>
              </Form>
            </div>
          ) : (
            <Alert variant="warning" className="text-center" style={{fontFamily:'body'}}>
              Could not load MFA setup data. Please check your system
              administrator permissions.
            </Alert>
          )}
        </Card.Body>
      </Card>
    </div>
  );
};

export default MfaSetupPage;
