import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import heroImage from "@/assets/Images/headerimage.png";
import { useNavigate } from "react-router-dom";
const Hero = () => {
    const navigate = useNavigate();
    return (_jsxs("section", { className: "relative min-h-screen flex items-center justify-center overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 bg-cover bg-center", style: { backgroundImage: `url(${heroImage})` }, children: _jsx("div", { className: "absolute inset-0", style: { background: 'var(--hero-gradient)' } }) }), _jsxs("div", { className: "relative z-10 container mx-auto px-4 sm:px-6 py-24 sm:py-32 text-center", children: [_jsxs("h1", { className: "text-3xl sm:text-4xl md:text-6xl lg:text-7xl font-bold text-primary-foreground mb-4 sm:mb-6 leading-tight", children: ["Start Your journey to", _jsx("br", { className: "hidden sm:block" }), "better mental health"] }), _jsx("p", { className: "text-base sm:text-lg md:text-xl lg:text-2xl text-primary-foreground/90 mb-8 sm:mb-12 max-w-3xl mx-auto px-4", children: "Obeeoma provides comprehensive mental health services with a personalized approach to help you achieve emotional well-being and resilience." }), _jsxs("div", { className: "flex flex-col sm:flex-row items-center justify-center gap-3 sm:gap-4 mb-8 sm:mb-12 px-4", children: [_jsx(Button, { variant: "hero", size: "lg", className: "w-full sm:w-auto text-base sm:text-lg px-6 sm:px-8 py-5 sm:py-6", onClick: () => navigate("/employer-dashboard"), children: "Sign up for my organization" }), _jsx(Button, { variant: "outline", size: "lg", className: "w-full sm:w-auto text-base sm:text-lg px-6 sm:px-8 py-5 sm:py-6", children: "Sign In" })] }), _jsxs("div", { className: "flex flex-wrap items-center justify-center gap-3", children: [_jsx(Badge, { variant: "secondary", className: "px-4 py-2 text-sm bg-background/90 backdrop-blur-sm", children: "Mental Health Assessments" }), _jsx(Badge, { variant: "secondary", className: "px-4 py-2 text-sm bg-background/90 backdrop-blur-sm", children: "Skills Learning" }), _jsx(Badge, { variant: "secondary", className: "px-4 py-2 text-sm bg-background/90 backdrop-blur-sm", children: "Feedback" }), _jsx(Badge, { variant: "secondary", className: "px-4 py-2 text-sm bg-background/90 backdrop-blur-sm", children: "EAP" })] })] })] }));
};
export default Hero;
