

server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Try to serve files directly, then fall back to index.html for React Router
        try_files $uri $uri/ /index.html;
    }

    # Configure CORS headers, compression, or caching here //still missing
    
}